language: python
python:
  - "2.7"

env:
  - DB="POSTGRESQL"
  - DB="MYSQL"

services:
  - mysql
  - postgres

before_install:
  - pip install codecov

install:
  - pip install -e git+https://github.com/tonioo/modoboa.git#egg=modoboa
  - pip install -q factory-boy testfixtures
  - pip install -q psycopg2 mysqlclient
  - python setup.py -q develop

before_script:
  - psql -c 'create database modoboa_test;' -U postgres
  - psql -c 'create database amavis_test;' -U postgres
  - mysql -e "create database IF NOT EXISTS modoboa_test;" -uroot
  - mysql -e "CREATE USER 'modoboa'@'localhost' IDENTIFIED BY 'modoboa'" -uroot;
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'modoboa'@'localhost';" -uroot;
  - mysql -e "create database IF NOT EXISTS amavis_test;" -uroot
  - mysql -e "CREATE USER 'amavis'@'localhost' IDENTIFIED BY 'amavis'" -uroot;
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'amavis'@'localhost';" -uroot;

script:
  - cd test_project
  - coverage run --source ../modoboa_amavis manage.py test modoboa_amavis

after_success:
  - codecov

